package de.noname.pizza4c.utils;

import java.util.Random;

public class NameUtils {
    private static final String[] ADJECTIVES = new String[]{
            "ravishing",
            "outstanding",
            "mimic",
            "famous",
            "cheerful",
            "livid",
            "obstinate",
            "exhausted",
            "graceful",
            "outrageous",
            "radical",
            "childish",
            "snobbish",
            "miserly",
            "amiable",
            "disgusting",
            "awful",
            "humorous",
            "fanciful",
            "pathetic",
            "windy",
            "dusty",
            "bashful",
            "freaky",
            "chilly",
            "stormy",
            "humid",
            "bountiful",
            "jubilant",
            "irritated",
            "patient",
            "dizzy",
            "skeptical",
            "puzzled",
            "perplexed",
            "over-whelmed",
            "jovial",
            "hyper",
            "squirrely",
            "jittery",
            "sensational",
            "elegant",
            "gleeful",
            "flabbergasted",
            "dreary",
            "impish",
            "sneaky",
            "horrid",
            "monsterous",
    };

    private static final String[] ANIMALS = new String[]{
            "Ant",
            "Antelope",
            "Ape",
            "Ass",
            "Badger",
            "Bat",
            "Bear",
            "Beaver",
            "Bird",
            "Boar",
            "Camel",
            "Canary",
            "Cat",
            "Cheetah",
            "Chicken",
            "Chimpanzee",
            "Chipmunk",
            "Cow",
            "Crab",
            "Crocodile",
            "Deer",
            "Dog",
            "Dolphin",
            "Donkey",
            "Duck",
            "Eagle",
            "Elephant",
            "Ferret",
            "Fish",
            "Fox",
            "Frog",
            "Goat",
            "Hamster",
            "Hare",
            "Horse",
            "Kangaroo",
            "Leopard",
            "Lion",
            "Lizard",
            "Mole",
            "Monkey",
            "Mousedeer",
            "Mule",
            "Ostritch",
            "Otter",
            "Panda",
            "Parrot",
            "Pig",
            "Polecat",
            "Porcupine",
            "Rabbit",
            "Rat",
            "Rhinoceros",
            "Seal",
            "Sheep",
            "Snake",
            "Squirrel",
            "Tapir",
            "Toad",
            "Tiger",
            "Tortoise",
            "Walrus",
            "Whale",
            "Wolf",
            "Zebra",
    };

    private static final String[] COLORS = new String[]{
            "Amber",
            "Beige",
            "Black",
            "Blue",
            "Brown",
            "Crimson",
            "Cyan",
            "Gray",
            "Green",
            "Indigo",
            "Magenta",
            "Orange",
            "Pink",
            "Purple",
            "Red",
            "Violet",
            "White",
            "Yellow",
    };

    public static Name generateNewName() {
        Random random = new Random(System.currentTimeMillis());

        var adjective = ADJECTIVES[random.nextInt(ADJECTIVES.length)];
        var colors = COLORS[random.nextInt(COLORS.length)];
        var animal = ANIMALS[random.nextInt(ANIMALS.length)];

        Name name = new Name();
        name.setLongName(adjective + colors + animal);
        name.setShortName((adjective.charAt(0) + "" + colors.charAt(0) + "" + animal.charAt(0)).toUpperCase());
        return name;
    }
}
